# Generated by Django 2.2.9 on 2020-06-06 11:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('headers', wagtail.core.fields.StreamField([('h_banner', wagtail.core.blocks.StructBlock([('banner_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', help_text='The bold header text at the frontpage slider', null=True)), ('banner_subhead', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', help_text='The content of the frontpage slider element', null=True)), ('banner_image', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Big, high resolution slider image', null=True))], blank=False, icon='title', null=True)), ('code', wagtail.core.blocks.RawHTMLBlock(blank=True, classname='full', icon='code', null=True))], null=True)),
                ('sections', wagtail.core.fields.StreamField([('s_about', wagtail.core.blocks.StructBlock([('info_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', help_text='The bold header text at the frontpage slider', null=True)), ('info_subhead', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', help_text='The content of the frontpage slider element', null=True)), ('info_image', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Big, high resolution slider image', null=True)), ('info_image_position', wagtail.core.blocks.ChoiceBlock(blank=False, choices=[('left', 'left'), ('right', 'right')], icon='cup', null=True))], blank=False, icon='radio-empty', null=True)), ('s_boxes', wagtail.core.blocks.StructBlock([('boxes_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', help_text='Bold header text', null=True)), ('boxes_displayhead', wagtail.core.blocks.BooleanBlock(blank=True, default=True, help_text='Whether or not to display the header', null=True, required=False)), ('boxes_collums', wagtail.core.blocks.StreamBlock([('box_collum', wagtail.core.blocks.StructBlock([('collum_image', wagtail.images.blocks.ImageChooserBlock(blank=False, help_text='Icon representating the below content', null=True)), ('collum_head', wagtail.core.blocks.CharBlock(blank=False, classname='full title', help_text='The bold header text at the frontpage slider', null=True)), ('collum_subhead', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', help_text='The content of the frontpage slider element', null=True)), ('collum_paragraph', wagtail.core.blocks.RichTextBlock(blank=False, classname='full', help_text='Formatted text', null=True))], blank=False, icon='cogs', null=True))], blank=False, max_num=3, null=True))], blank=False, icon='pilcrow', null=True))], null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_title', models.CharField(max_length=255, null=True)),
                ('button_embed', models.CharField(blank=True, max_length=255, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('button_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
        ),
    ]
